# Generated by Django 4.0.3 on 2022-07-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='url_image',
            field=models.URLField(null=True),
        ),
    ]
