# Generated by Django 4.0.3 on 2022-08-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlist_user_alter_auctionlist_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
