# Generated by Django 4.0.3 on 2022-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlist_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
